name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:


  build:
    runs-on: windows-latest
    steps:
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        mssystem: MINGW64
        install: >-
          git
          mingw-w64-x86_64-go
          mingw-w64-x86_64-mpv
          

    - uses: actions/checkout@v3

    - name: Build

      run: go build -o AynaLivePlayer.exe -ldflags -H=windowsgui app/gui/main.go

