name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Add Dependency
      run: sudo apt install mpv

    - name: Build

      run: GOOS=Windows go build -o AynaLivePlayer.exe -ldflags -H=windowsgui app/gui/main.go

